config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :animals do
    member do
      post :search
    end
    resources :bookings
  end

  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'animals/:id/dead', to: 'animals#dead', as: :dead_animal
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :bookings, dependent: :destroy
  belongs_to :user

  has_one_attached :photo

  validates :name, presence: true
  validates :breed, presence: true
  validates :birth_date, presence: true
  validates :colour, presence: true
  validates :address, presence: true
  validates :price, presence: true
  validates :description, presence: true

  scope :top_six, -> {
    joins(:bookings).group("animals.id").order("AVG(bookings.review_rating) DESC").limit(3)
  }


  def average
    if bookings.empty?
      return 0.0
    else
      bookings.average(:review_rating)
      # ratings = self.bookings.pluck(:review_rating)
      # return ratings.reduce(:+) / ratings.size
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :animal
  belongs_to :user
  validates :date_in, presence: true
  validates :date_out, presence: true
  # validates :review_rating, inclusion: { in: [1, 2, 3, 4, 5] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  has_many :animals, dependent: :destroy
  has_many :bookings, dependent: :destroy
  # has_many :requests, through: :animals, class_name: 'Booking', foreign_key: :booking_id
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: %I[show edit update dead]
  def index
    if params["search"]["query"].blank?
      @animals = policy_scope(Animal).order(created_at: :desc)
    else
      search = params["search"]["query"]
      @animals = policy_scope(Animal).near(search, 10)
    end

    @markers = @animals.map do |animal|
      {
       lat: animal.latitude,
       lng: animal.longitude,
       infoWindow: render_to_string(partial: "info_window", locals: { animal: animal }),
       image_url: helpers.asset_url('https://icon-library.net/images/llama-icon/llama-icon-29.jpg')
      }
    end
  end

  def show
    authorize @animal
  end

  def new
    @animal = Animal.new
    authorize @animal
  end

  def create
    @animal = Animal.new(animal_params)
    authorize @animal

    @animal.user = current_user

    if @animal.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    authorize @animal
  end

  def update
    if @animal.update(animal_params)
      redirect_to @animal, notice: "#{@animal.name} was successfully updated."
    else
      render :edit
    end
    authorize @animal
  end

  def dead
    @animal.dead = true
    @animal.save
    redirect_to dashboard_path(@animal)
  end


  private

  def animal_params
    params.require(:animal).permit(:name, :birth_date, :address, :price, :photo, :description, :breed, :colour)
  end

  def set_animal
    @animal = Animal.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :bio, :avatar])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %I[show edit update]
  def index
    @bookings = Booking.all
    raise
  end

  def show
    authorize @booking
  end

  def new
    @animal = Animal.find(params[:animal_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @animal = Animal.find(params[:animal_id])
    @booking.animal = @animal
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
    authorize @booking
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to dashboard_path
  end

  def edit
    @booking = Booking.find(params[:id])
    respond_to do |format|
      format.html do
        render 'edit', booking: @booking
      end
      format.js do
        j render 'edit', booking: @booking
      end

    end
    authorize @booking
  end

  def update
    if params[:booking][:status].present?
      @booking.update(status: params[:booking][:status])
    end

    if @booking.update(booking_params)
      redirect_to dashboard_path
    else
      render :edit
    end
    authorize @booking
  end

  private

  def booking_params
    params.require(:booking).permit(:date_in, :date_out, :review_rating, :review_description, :status)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :index ]
  def home
    # animals = Animal.all
    # ratings = []
    # animals.each do |animal|
    #   animal.bookings.each do |booking|
    #     ratings << booking.review_rating.to_i
    #   end
    #   average = ratings.sub.fdiv(ratings.size).round(2)
    # end
    # @animals = Animal.all.order(average: :desc).first(6)
    @animals = Animal.top_six
  end

  def dashboard
    @animals = current_user.animals # Animal.where(user: current_user)
    # @animal = Animal.new
    @bookings = current_user.bookings
    # @requests = current_user.requests
    @requests = []
    current_user.animals.each do |animal|
      animal.bookings.each do |b|
        @requests << b
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_edit_animals.html.erb
<div class="card card-body">
        <h2>Change <%= @animal.name %>'s  infos</h2>
        <%= simple_form_for(@animal) do |f| %>
          <div class="row justify-content-between">
            <div class="col-3">
              <%= f.input :name, placeholder: 'Happy' %>
            </div>
            <div class="col-6">
              <%= f.input :breed, as: :radio_buttons, collection: ['Alpaga', 'Camel','Llama'], wrapper: :vertical_collection_inline %>
            </div>
            <div class="col-3">
              <%= f.input :price, placeholder: '100' %>
            </div>
           </div>
          <%= f.input :birth_date %>
          <%= f.input :colour, as: :radio_buttons, collection: ['White', 'Black','Brown', 'Grey', 'Beige', 'Red'], wrapper: :vertical_collection_inline %>
          <%= f.input :address, placeholder: '16 villa Gaudelet, Paris' %>
          <%= f.input :description, placeholder: 'Describe your animal :)' %>
          <%= f.input :photo, as: :file %>

          <%= f.submit "Save !", class: 'btn btn-primary ml-2' %>
        <% end %>
      </div>

app/views/animals/_info_window.html.erb
<%= link_to animal_path(animal) do %>
  <div id= "info-map-text">
    <h2><%= animal.name %></h2>
    <p><%= animal.address %></p>
    <p><%#= animal.description %></p>
  </div>
<% end  %>

app/views/animals/dead.html.erb
<h2> Nos Vemos pronto </h2>

<h1><% @animal.name %></h1>

app/views/animals/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 mt-3">
      <h1 class="mb-4">Update <%= @animal.name %>'s details</h1>
      <%= simple_form_for(@animal) do |f| %>
        <%= f.input :name  %>
        <%= f.input :breed, collection: ['Alpaga', 'Camel','Llama'] %>
        <%= f.input :birth_date %>
        <%= f.input :colour %>
        <%= f.input :address %>
        <%= f.input :description %>
        <%= f.input :photo %>
        <%= f.input :price %>
        <%= f.submit 'Update', class: 'btn btn-primary mr-2' %>
        <%= link_to 'Cancel', animal_path(@animal), class: 'btn btn-secondary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/animals/index.html.erb
 <div class="container">

  <div
    id="map"
    style="width: 100%;
    height: 250px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    class = "mt-5">
  </div>

    <h2 class="mt-4 mb-4">Animal list</h2>

    <div class="cards">
    <% @animals.each do |animal| %>

    <div class="card-trip small">
      <%  if animal.photo.class == String  %>
      <img src="https://i.pinimg.com/originals/e9/2e/40/e92e408aac9f853b4a03173859f91d87.jpg" alt="">
      <% else %>
      <%= cl_image_tag animal.photo.key %>
      <% end %>
      <div class="card-trip-infos">
        <div>
          <h2><%= animal.name %></h2>
          <p><%= animal.breed %></p>
          <p><%= animal.description.slice(0, 33) %> <%= animal.description.length > 33 ? "..." : "" %></p>
          <% ratings = [] %>
          <p><i class="far fa-star"></i><% animal.bookings.each do |booking| %>
          <% ratings << booking.review_rating.to_i %>
          <% end %>
          <% average = ratings.sum.fdiv(ratings.size) %>
          <%= average.nan? ? "no ratings" : ratings.sum.fdiv(ratings.size) %></p>
        </div>
        <h2 class="card-trip-pricing">€<%= animal.price %></h2>
        <%= cl_image_tag animal.user.photo.key, width: 60, height: 50, crop: :thumb, gravity: :face, class: "card-trip-user avatar" %>
        </div>

          <% if policy(Animal).show? %>
            <%= link_to 'More info', animal_path(animal), class: 'btn btn-outline-primary mb-3 ml-3' %>
          <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/animals/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="card col-12 col-lg-6 mt-4">
      <div class="card-body">
        <h2>Add an animal</h2>
        <%= simple_form_for(@animal) do |f| %>
          <%= f.input :name, placeholder: 'Happy' %>
          <%= f.input :breed, as: :radio_buttons, collection: ['Alpaga', 'Camel','Llama'], wrapper: :vertical_collection_inline %>
          <%= f.input :birth_date %>
          <%= f.input :colour, as: :radio_buttons, collection: ['White', 'Black','Brown', 'Grey', 'Beige', 'Red'], wrapper: :vertical_collection_inline %>
          <%= f.input :address, placeholder: '16 villa Gaudelet, Paris' %>
          <%= f.input :description, placeholder: 'Describe your animal :)' %>
          <%= f.input :photo, as: :file %>
          <%= f.input :price, placeholder: '100' %>
          <div class='d-flex'>
            <%= link_to 'Cancel', dashboard_path, class: 'btn btn-info' %>
            <%= f.submit 'Add my animal', class: 'btn btn-primary ml-2' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/animals/show.html.erb
<div class="container mt-5">
  <div class="row d-flex justify-content-between">
    <div class="col-6">
      <div class="show-card">
        <div class="animal-card">
          <%  if @animal.photo.class == String  %>
            <img src="https://i.pinimg.com/originals/e9/2e/40/e92e408aac9f853b4a03173859f91d87.jpg" alt="">
          <% else %>
            <%= cl_image_tag @animal.photo.key if @animal.photo.attached? %>
          <% end %>
          <div class="animal-infos p-3" >
            <h1> <%= @animal.name %> the <%= @animal.breed %></h1>
            <p> <strong>Breed: </strong> <%= @animal.breed %></p>
            <p> <strong>Description: </strong> <%= @animal.description %></p>
            <p> <strong>Price per day: </strong> <%= @animal.price %>€</p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-6 update-or-book-card">
      <% if policy(@animal).update? %>
        <div>
          <%= render 'edit_animals' %>
        </div>
      <% else %>
        <div class="calendar_booking">
          <%=render 'shared/bookings_new', booking: Booking.new %>
        </div>
        <% if @animal.bookings.present? %>
          <h3 class= "mt-4 mb-4"><strong>Have a look at reviews:</strong></h3>
          <% @animal.bookings.each do |booking| %>
            <% booking.status == "completed" %>
            <% booking.review_description %>
            <p class="mb-3"><%= '⭐️' * booking.review_rating.to_i %>   <%= booking.review_description %></p>
          <% end %>
        <% end %>
      <% end %>

    </div>
  </div>
    <!-- <div class="mt-4"> -->
      <%# if policy(@animal).update? %>
        <%#= link_to "Update #{@animal.name}", edit_animal_path(@animal), class: "btn btn-outline-primary mr-4" %>
      <%#= link_to "Kill #{@animal.name}", dead_animal_path(@animal), data: {confirm: "Killing #{@animal.name} ?"}, class: "btn btn-outline-primary mr-4"%>
      <%# else %>
        <%#= link_to "Book #{@animal.name}", new_animal_booking_path(@animal), class: 'btn btn-outline-primary mr-4' %>
      <%# end %>
      <%#= link_to "Back to my ", dashboard_path, class: 'btn btn-outline-primary mr-4' %>
    <!-- </div> -->

  </div>




</div>

app/views/bookings/_edit.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel"></h4>
</div>
<div class="modal-body">
  <%= simple_form_for [booking.animal, booking] do |f| %>
    <%= f.input :review_rating, collection: [ 1, 2, 3, 4, 5, ] %>
    <%= f.input :review_description %>
    <hr>
    <%= f.submit 'Confirm', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', dashboard_path, class: 'btn btn-secondary' %>
  <% end %>
</div>
<!-- <div class="modal-footer"> -->
<!-- </div> -->

app/views/bookings/edit.html.erb
<%= render 'edit', booking: @booking %>

app/views/bookings/edit.js.erb
$("#modal-window-<%= @booking.id %>").find(".modal-content").html("<%= j (render 'bookings/edit', booking: @booking) %>");
$("#modal-window-<%= @booking.id %>").modal();

app/views/bookings/index.html.erb
<div class="container">
  <div class="row pt-4">
    <div class="col-12">
      <h2 >Booking list</h2>
    </div>
  </div>

  <div class="cards">
    <% @bookings.each do |booking| %>
    <div class="card-trip">
      <div class="card-trip-infos">
        <div>
          <h2> <b>Animal name: </b> <%= booking.animal.name %></h2>
            <p>Date in: <%= booking.date_in %></p>
            <p>Date out: <%= booking.date_out %></p>
            <p>Status: <%= booking.status %></p>
        <%= link_to "More info", animal_booking_path(booking.animal, booking), class: 'btn btn-outline-primary mb-2 ml-2 mt-2' %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<%= simple_form_for [@animal, @booking] do |f| %>
  <%= f.input :date_in  %>
  <%= f.input :date_out %>
  <%= f.submit 'Create new booking', class: 'btn btn-primary' %>
<% end %>

app/views/bookings/show.html.erb
<div class="container">

  <h2 class="mt-5">Booking #<%= @booking.id %></h2>

  <ul>
    <li>Animal name: <b><%= @booking.animal.name %></b></li>
    <li>Date in: <%= @booking.date_in %></li>
    <li>Date out: <%= @booking.date_out %></li>
    <li>Status: <%= @booking.status %></li>
  </ul>

  <% unless @booking.review_rating.nil? %>
    <div class="card mb-3">
      <div class="card-body">
        <p>Review from: <b><%= @booking.user.first_name %> <%= @booking.user.last_name %></b></p>
        <p><%= '⭐️' * @booking.review_rating %></p>
        <p><%= @booking.review_description %></p>
      </div>
    </div>
  <% else %>
    <% if policy(@booking).update? %>
        <% if @booking.status == 'completed' %>
          <p><%= link_to "Add review", edit_animal_booking_path(@booking.animal, @booking), class: 'btn btn-secondary' %></p>
        <% else %>
          <p><%= link_to "Change booking status", edit_animal_booking_path(@booking.animal, @booking), class: "mt-2 btn btn-secondary"%></p>
        <% end %>
    <% end %>
  <% end %>


  <p><%= link_to "Delete booking", animal_booking_path(@booking.animal), method: :delete, data: { confirm: "Delete Booking?"}, class: "btn btn-danger"%></p>
  <p><%= link_to "Back to bookings", dashboard_path, class: 'btn btn-secondary' %></p>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <%= favicon_link_tag asset_path('logo.png') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Camelove</title>
    <style>
      @import url('https://fonts.googleapis.com/css?family=Odibee+Sans&display=swap');
      </style>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>

    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/_animals.html.erb
 <div class="container">
  <div class="d-flex justify-content-between pt-4">
    <h2 >Animal list</h2>
    <div>
      <%= link_to 'Add an animal', new_animal_path, class: 'btn btn-primary' %>
    </div>
  </div>

  <div class="cards-large mt-4 mb-4">
    <% @animals.each do |animal| %>
      <% if animal.dead == false %>
        <div class="card-trip">
      <%  if animal.photo.class == String  %>
      <img src="https://www.solidbackgrounds.com/images/2560x1440/2560x1440-davys-grey-solid-color-background.jpg" alt="">
      <% else %>
      <%= cl_image_tag animal.photo.key if animal.photo.attached? %>
      <% end %>
      <div class="card-trip-infos">
        <div>
          <h2><%= animal.name %></h2>
          <p><%= animal.breed %></p>
          <p><%= animal.description.slice(0, 50) %> <%= animal.description.length > 50 ? "..." : "" %></p>
          <% ratings = [] %>
          <p><i class="far fa-star"></i><%= animal.average %>
        </div>
        <h2 class="card-trip-pricing">€<%= animal.price %></h2>
        </div>
        <%= link_to 'More info', animal_path(animal), class: 'btn btn-outline-primary mb-3 ml-3' %>
    </div>
      <% end %>
    <% end %>
    </div>
  </div>

app/views/pages/_bookings.html.erb
 <div class="container">
    <div class="row pt-4">
      <div class="col-12">
      <h2 >Booking list</h2>
      </div>
   </div>




    <div class="row pt-4 d-flex justify-content-between">
      <% @bookings.each do |booking| %>
        <% if booking.status != 'completed' %>
          <div class="card-trip list d-flex justify-content-between m-4">
          <div class="animal-thumb">
            <%= cl_image_tag booking.animal.photo.key, width:80, height: 80, class:"img-thumbnail mt-2 mr-2 ml-2" %>
          </div>
            <div class="card-trip-infos-list">
              <div>
                <h2><%= booking.animal.name %></h2>
                  <p> From <% date_in = booking.date_in %>
                  <%= date_in.strftime('%e %b') %>
                  <% date_out = booking.date_out %>
                  to <%= date_out.strftime('%e %b') %></p>

                  <p>Status: <%= booking.status %></p>
                  <%#= link_to "More info", animal_booking_path(booking.animal, booking), class: 'btn btn-outline-primary mb-2 ml-2 mt-2' %>
              </div>
            </div>
          </div>
        <% end %>

       <% end %>
    </div>

    <div class="history row pt-2 d-flex justify-content-between">
      <h2>Booking history</h2>
       <% @bookings.each do |booking| %>
        <% if booking.status == 'completed' %>
          <div class="booking_animal_card w-100">
            <div class="d-flex justify-content-between">
              <h3><%= booking.animal.name %></h3>
              <p><% date_in = booking.date_in %>
                <%= date_in.strftime('%e %b') %>
                <% date_out = booking.date_out %>
                to <%= date_out.strftime('%e %b') %></p>
            </div>
            <% unless booking.review_rating.present? %>
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-window-<%= booking.id %>">
                Add a review
              </button>
            <% else %>
              <p><%= '⭐️' * booking.review_rating %> <%= booking.review_description %></p></div>
            <% end %>
          </div>
        <% end %>
        <div id="modal-window-<%= booking.id %>" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <%= render 'bookings/edit', booking: booking %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/pages/_requests.html.erb
 <div class="container">
    <div class="row pt-4">
      <div class="col-12">
      <h2 >Requests</h2>
      </div>
   </div>

  <div class=" cards-large">
      <% @requests.each do |request| %>
        <div class="notification">
          <div class="notification-content">
            <p><small class="first_line"><strong><%= request.animal.name %></strong>  booked by <%= request.user.first_name %> from <%= request.date_in %> to <%= request.date_out %></small></p>
           <p>
             <%= simple_form_for [request.animal, request] do |f| %>
              <%= f.input :status, collection: ['pending', 'confirmed', 'declined', 'completed'], label: false %>
              <%= f.submit class: 'btn btn-ghost'%>
              <% end %>
           </p>

          </div>
         </div>
      <% end %>
    </div>

  </div>

app/views/pages/_review_form.html.erb
<!-- CREATE REVIEWS -->
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Add a review</h4>
</div>
<div class="modal-body">
  <%= simple_form_for [request.animal, request] do |f| %>
      <%= f.input :review_rating, collection: [ 1, 2, 3, 4, 5, ] %>
      <%= f.input :review_description %>
      <%= f.submit 'Confirm', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', dashboard_path, class: 'btn btn-secondary' %>
    <% end %>
</div>
<div class="modal-footer">
  <button class="btn btn-primary">Save</button>
</div>

app/views/pages/dashboard.html.erb
<div class="container-fluid">
  <div class="row d-flex justify-content-around m-3">

    <div class="card col-4">
      <%= render 'animals' %>
      <!-- <h2>Killed Animals</h2> -->
      <%#= render template: 'animals/dead' %>
    </div>

    <div class="card col-3">
      <%= render 'requests' %>
    </div>


    <div class="card col-4">
      <%= render 'bookings' %>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://www.tripsavvy.com/thmb/lM9zx1S99Qmfij2Xf7kyxfIn7zM=/4256x2832/filters:no_upscale():max_bytes(150000):strip_icc()/llama-overlooking-ruins-of-the-ancient-city-of-machu-picchu--peru--639822048-5ba3d1e1c9e77c0050d73538.jpg')">
  <div class="container">
    <h1 class="mb-5">Rent your <strong>llamas, alpacas and more</strong> <br>where you want!</h1>
    <%= simple_form_for :search, url: animals_path, method: :get do |f| %>
      <div class="search-form-control form-group">
      <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Enter an address" />
      <button name="button" type="submit" class="btn btn-primary">
        <i class="fas fa-search"></i> Search
      </button>
  </div>

    <% end %>
  </div>
</div>

<div class="container mt-3">
  <h2>The best animals</h2>
  <p>Discover a selection of the best rated camelidae in the world</p>
  <div class="cards">
    <% @animals.each do |animal| %>
    <%= link_to animal_path(animal) do %>
    <div class="card-trip small">
      <%  if animal.photo.class == String  %>
      <img src="https://i.pinimg.com/originals/e9/2e/40/e92e408aac9f853b4a03173859f91d87.jpg" alt="">
      <% else %>
      <%= cl_image_tag animal.photo.key %>
      <% end %>
      <div class="card-trip-infos">
        <div>
          <h2><%= animal.name %></h2>
          <p><%= animal.description.slice(0, 33) %><%= animal.description.length > 33 ? "..." : "" %></p>
          <p><i class="far fa-star"></i><%= animal.average %></p>
        </div>
        <h2 class="card-trip-pricing">€<%= animal.price %></h2>
        <%= cl_image_tag animal.user.photo.key, width: 60, height: 50, crop: :thumb, gravity: :face, class: "card-trip-user avatar" %>
        </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

<!--  <#%= cl_image_tag @article.photo.key, height: 300, width: 400, crop: :fill %>
 -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Dashboard", dashboard_path, class: "btn btn-outline-primary mt-1 mr-2" %>
        </li>
        <!-- <li class="nav-item">
          <%#= link_to "My bookings", animal_booking_path, class: "nav-link" %>
        </li> -->
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.key, width: 50, height: 50, crop: :thumb, gravity: :face, class: "rounded-circle dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" } %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%#= link_to "My dead animals", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>